[QA-329] Adding pipe method.
Aleksandras-V/C-hands-on-programming-2 pull request #4
Opened 2022-02-25 12:25 UTC by Aleksandras-V

2022-02-25 12:33 UTC, RomainChaumontet approved these changes
Great work!

2022-03-01 09:16 UTC, ivan-estonia requested changes

2022-03-01 09:16 UTC, ivan-estonia commented on ipc_sendfile.h
> +#define pipe_size 4096
Never seen defines named with small letters. It is better to use all capital letters.

2022-03-01 09:16 UTC, ivan-estonia commented on ipc_receivefile.c
> +		printf("ERROR: Malloc");
```suggestion
		fprintf(stderr, "ERROR: Malloc");
```

2022-03-01 09:16 UTC, ivan-estonia commented on ipc_receivefile.c
> +	} while (status == -1);
```suggestion
	while (-1 == access (pipe_name, F_OK)) {
	        sleep (2);					
	}
	
	fd = open(pipe_name, O_RDONLY);
	if (fd == -1) {
		perror ("open pipe");
		exit (EXIT_FAILURE);
	}
```

2022-03-01 09:16 UTC, ivan-estonia commented on ipc_receivefile.c
> +			exit(EXIT_FAILURE);
`close(pipe_name)`

2022-03-01 09:16 UTC, ivan-estonia commented on ipc_receivefile.c
> +			exit(EXIT_FAILURE);
`close(pipe_name)`

2022-03-01 09:16 UTC, ivan-estonia commented on ipc_receivefile.c
> +		exit(EXIT_FAILURE);
free(buffer);

2022-03-01 09:16 UTC, ivan-estonia commented on ipc_receivefile.c
> +			exit(EXIT_FAILURE);
`free(buffer);`

2022-03-01 09:16 UTC, ivan-estonia commented on ipc_receivefile.c
> +			exit(EXIT_FAILURE);
`free(buffer);`

2022-03-01 10:31 UTC, Aleksandras-V commented on ipc_receivefile.c
> +		exit(EXIT_FAILURE);
Corrected !

2022-03-01 10:31 UTC, Aleksandras-V commented on ipc_receivefile.c
> +			exit(EXIT_FAILURE);
Corrected !

2022-03-01 10:31 UTC, Aleksandras-V commented on ipc_receivefile.c
> +			exit(EXIT_FAILURE);
Corrected !

2022-03-01 10:31 UTC, Aleksandras-V commented on ipc_sendfile.h
> +#define pipe_size 4096
Corrected !

2022-03-01 10:43 UTC, baovu-unikie commented
I pulled the latest commit. Here are the errors:
![image](https://user-images.githubusercontent.com/97879325/156154471-e626bb34-ab52-45e6-9000-98fe4824e316.png)

2022-03-01 12:51 UTC, ivan-estonia approved these changes

2022-03-01 16:03 UTC, merged